django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='index'),
    path('', include('users.urls')), # redirects all user apps urls to users -> urls.py
    url(r'^accounts/', include('allauth.urls')),  # new for django all-auth
    url(r'^messages/', include('postman.urls', namespace='postman')), # added for postman
    path('ckeditor/', include('ckeditor_uploader.urls')), #added for ckeditor
    url(r'^community/', include('community.urls')),
    url(r'^garden/',include('garden.urls')),
    url(r'^map/',include('map.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/map/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = 'map'

urlpatterns =[
    # path(r'', TemplateView.as_view(template_name='map/index.html'), name='map_home'),
    path(r'', views.MapView, name='map_home'),
    path('produce_data/', views.produce_locations, name='loc'),
]

django_project/map/models.py
from django.db import models
from django.contrib.gis.db import models
from geopy import geocoders
from geopy.exc import GeocoderTimedOut
from django.contrib.gis.geos import Point



# Create your models here.
class Produce(models.Model):
    produceName     = models.CharField(max_length=20, default='')
    unit            = models.CharField(max_length=50, default='')
    producePrice    = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True, default=0.00)
    address         = models.CharField(max_length=20, default='')
    city            = models.CharField(max_length=20, default='')
    postal          = models.CharField(max_length=20, default='')
    loc             = models.PointField(default=Point(-114.080251,51.007831)) #WHAT IS THIS SRID????



    #objs    = models.GeoManager()

    # @property
    # def popupContent(self):
    #   return '<p><{}</p>'.format(self.produceName)

    def  __str__(self):
        return self.produceName


    #NOT WORKING YET :)
    # def geocode_address(self, address):
    # """Google Maps v3 API: https://developers.google.com/maps/documentation/geocoding/"""
    # # https://stackoverflow.com/questions/27914648/geopy-catch-timeout-error
    # googlelocator  = GoogleV3()
    # try:
    #     loc = geolocator.geocode(address, exactly_one=True, timeout=5)
    # except GeocoderTimedOut as e:
    #     print("GeocoderTimedOut: geocode failed on input %s with message %s" % (address, e.msg))
    # except AttributeError as e:
    #     print("AttributeError: geocode failed on input %s with message %s" % (address, e.msg))

django_project/map/forms.py
from django import forms
from .models import Produce
from django.core import validators

def check_postal_code(value):
    #Add conditions
    #raise forms.ValidationError("INCORRECT POSTAL CODE")
    pass

class AddSaleItem(forms.ModelForm):
    botcatcher = forms.CharField(required=False,
                                widget=forms.HiddenInput,
                                validators=[validators.MaxLengthValidator(0)])
    class Meta:
        model = Produce
        fields =[
            'produceName',
            'unit',
            'producePrice',
            'address',
            'city',
            'postal'
        ]




    # produceName     = forms.CharField(label= 'Produce', widget=forms.TextInput(attrs={'placeholder': 'Spinach'}) )
    # unit            = forms.CharField(label= 'Sale Unit (bag, lbs, number, etc)', widget=forms.TextInput(attrs={'placeholder': 'bag'}) )
    # producePrice    = forms.DecimalField(label= 'Price',widget=forms.TextInput(attrs={'placeholder': '2.00'}) )
    # address         = forms.CharField(label= 'Address', widget=forms.TextInput(attrs={'placeholder': '123 Food St'}) )
    # city            = forms.CharField(label= 'City', widget=forms.TextInput(attrs={'placeholder': 'Calgary'}) )
    # postal          = forms.CharField(label= 'Postal Code',widget=forms.TextInput(attrs={'placeholder': 'T2G1G1'}) )

django_project/map/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.core.serializers import serialize
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Produce
from .forms import AddSaleItem

def MapView(request):
    if request.method == "POST":
        form = AddSaleItem(request.POST or None)
        if form.is_valid():
            print("Your item has been added to the database!")
            form.save(commit=True)
            #obj = form.save(commit=False)
            #obj.save()
        return redirect('map:map_home')
    else:
        form=AddSaleItem()

    return render(request, 'map/index.html', {'form': form})

def produce_locations(request):
    produce_locs = serialize('geojson', Produce.objects.all())
    return HttpResponse(produce_locs, content_type='json')

django_project/map/templates/map/index.html
{% extends "base.html" %}
{% load static %}
{% load leaflet_tags %}

{% block content %}
<h1 class="text-center">Seach for Veggies!</h1>
<br>
<div class="modal-body row">
  <div class="col-md-6">
    <!-- Form to add new item -->
    <h5>Add Item for Sale</h5>
    <form method='POST'>
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" class="btn btn-primary" value="Submit">
    </form>

    <!-- <form method="POST">
      {% csrf_token %}
      <table>
        {{ form.as_p }}
      </table> -->
      <!-- <button type="submit" name="button">Submit</button> -->

    <!-- </form> -->
  </div>
  <div class="col-md-6">
    {% leaflet_js %}
    {% leaflet_css %}
    <style type="text/css">#gis {width:100%;height:100%;}</style>
    <script type="text/javascript" src="{% static 'dist/leaflet.ajax.js' %}"> </script>
    <script type="text/javascript">
      function produce_layers(map,options){
        var locations = new L.GeoJSON.AJAX("{% url 'map:loc' %}", {
          onEachFeature: function(feature,layer){
            layer.bindPopup(feature.properties.produceName);
        }});
          locations.addTo(map);
      }
    </script>

    {% leaflet_map "gis" callback="window.produce_layers" %}
  </div>



</div>
{% endblock %}








<!-- <!DOCTYPE html>

<html lang="en" dir="ltr">
{% load static %}
{% load leaflet_tags %}
  <head>
    <meta charset="utf-8">
    <title>Search for Veggies!</title>
    {% leaflet_js %}
    {% leaflet_css %}
    <!-- ADD MAP TO PAGE -->
    <!-- <style type="text/css">#gis {width:50%;height:25%;}</style> -->
    <!-- <script type="text/javascript" src="{% static 'dist/leaflet.ajax.js' %}"> </script> -->
  <!-- </head> -->
  <!-- <body> -->
    <!-- <h1>Produce Search</h1>
    <script type="text/javascript">
      function produce_layers(map,options){
        var locations = new L.GeoJSON.AJAX("{% url 'map:loc' %}", { -->
          <!-- // onEachFeature: function(feature,layer){
          //   layer.bindPopup(feature.properties.produceName);
        });
          locations.addTo(map);
      } -->
    <!-- </script>

    {% leaflet_map "gis" callback="window.produce_layers" %}
  </body> -->
<!-- </html> -->