django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='index'),
    path('', include('users.urls')), # redirects all user apps urls to users -> urls.py
    url(r'^accounts/', include('allauth.urls')),  # new for django all-auth
    url(r'^messages/', include('postman.urls', namespace='postman')), # added for postman
    path('ckeditor/', include('ckeditor_uploader.urls')), #added for ckeditor
    url(r'^community/', include('community.urls')),
    url(r'^garden/',include('garden.urls')),
    url(r'^map/',include('map.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/map/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = 'map'

urlpatterns =[
    # path(r'', TemplateView.as_view(template_name='map/index.html'), name='map_home'),
    path(r'', views.MapView, name='map_home'),
    path('produce_data/', views.produce_locations, name='loc'),
]

django_project/postman/urls.py
"""
If the default usage of the views suits you, simply use a line like
this one in your root URLconf to set up the default URLs::

    (r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),

Otherwise you may customize the behavior by passing extra parameters.

Recipients Max
--------------
Views supporting the parameter are: ``WriteView``, ``ReplyView``.
Example::
    ...View.as_view(max=3), name='write'),
See also the ``POSTMAN_DISALLOW_MULTIRECIPIENTS`` setting

User filter
-----------
Views supporting a user filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_user_filter(user):
        if user.get_profile().is_absent:
            return "is away"
        return None
    ...
    ...View.as_view(user_filter=my_user_filter), name='write'),

function interface:
In: a User instance
Out: None, False, '', 'a reason', or ValidationError

Exchange filter
---------------
Views supporting an exchange filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_exchange_filter(sender, recipient, recipients_list):
        if recipient.relationships.exists(sender, RelationshipStatus.objects.blocking()):
            return "has blacklisted you"
        return None
    ...
    ...View.as_view(exchange_filter=my_exchange_filter), name='write'),

function interface:
In:
    ``sender``: a User instance
    ``recipient``: a User instance
    ``recipients_list``: the full list of recipients or None
Out: None, False, '', 'a reason', or ValidationError

Auto-complete field
-------------------
Views supporting an auto-complete parameter are: ``WriteView``, ``ReplyView``.
Examples::
    ...View.as_view(autocomplete_channels=(None,'anonymous_ac')), name='write'),
    ...View.as_view(autocomplete_channels='write_ac'), name='write'),
    ...View.as_view(autocomplete_channel='reply_ac'), name='reply'),

Auto moderators
---------------
Views supporting an ``auto-moderators`` parameter are: ``WriteView``, ``ReplyView``.
Example::
    def mod1(message):
        # ...
        return None
    def mod2(message):
        # ...
        return None
    mod2.default_reason = 'mod2 default reason'
    ...
    ...View.as_view(auto_moderators=(mod1, mod2)), name='write'),
    ...View.as_view(auto_moderators=mod1), name='reply'),

function interface:
In: ``message``: a Message instance
Out: rating or (rating, "reason")
    with reting: None, 0 or False, 100 or True, 1..99

Others
------
Refer to documentation.
    ...View.as_view(form_classes=(MyCustomWriteForm, MyCustomAnonymousWriteForm)), name='write'),
    ...View.as_view(form_class=MyCustomFullReplyForm), name='reply'),
    ...View.as_view(form_class=MyCustomQuickReplyForm), name='view'),
    ...View.as_view(template_name='my_custom_view.html'), name='view'),
    ...View.as_view(success_url='postman:inbox'), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='view'),

"""
#from __future__ import unicode_literals

from django import VERSION
from django.conf import settings
from django.conf.urls import url
from django.urls import path
from django.urls import re_path
if VERSION < (1, 10):
    from django.core.urlresolvers import reverse_lazy
else:
    from django.urls import reverse_lazy
if getattr(settings, 'POSTMAN_I18N_URLS', False):
    from django.utils.translation import pgettext_lazy
else:
    def pgettext_lazy(c, m): return m
from django.views.generic.base import RedirectView

from .views import (InboxView, SentView, ArchivesView, TrashView,
        WriteView, ReplyView, MessageView, ConversationView,
        ArchiveView, DeleteView, UndeleteView, MarkReadView, MarkUnreadView)

app_name = 'postman'
urlpatterns = [
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^inbox/(?:(?P<option>m)/)?$'), InboxView.as_view(), name='inbox'),
    # path('inbox/', InboxView.as_view(), name='inbox'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^sent/(?:(?P<option>m)/)?$'), SentView.as_view(), name='sent'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^archives/(?:(?P<option>m)/)?$'), ArchivesView.as_view(), name='archives'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^trash/(?:(?P<option>m)/)?$'), TrashView.as_view(), name='trash'),
    url(pgettext_lazy('postman_url', r'^write/(?:(?P<recipients>[^/#]+)/)?$'), WriteView.as_view(), name='write'),
    url(pgettext_lazy('postman_url', r'^reply/(?P<message_id>[\d]+)/$'), ReplyView.as_view(), name='reply'),
    url(pgettext_lazy('postman_url', r'^view/(?P<message_id>[\d]+)/$'), MessageView.as_view(), name='view'),
    # Translators: 't' stands for 'thread'
    url(pgettext_lazy('postman_url', r'^view/t/(?P<thread_id>[\d]+)/$'), ConversationView.as_view(), name='view_conversation'),
    url(pgettext_lazy('postman_url', r'^archive/$'), ArchiveView.as_view(), name='archive'),
    url(pgettext_lazy('postman_url', r'^delete/$'), DeleteView.as_view(), name='delete'),
    url(pgettext_lazy('postman_url', r'^undelete/$'), UndeleteView.as_view(), name='undelete'),
    url(pgettext_lazy('postman_url', r'^mark-read/$'), MarkReadView.as_view(), name='mark-read'),
    url(pgettext_lazy('postman_url', r'^mark-unread/$'), MarkUnreadView.as_view(), name='mark-unread'),
    url(r'^$', RedirectView.as_view(url=reverse_lazy('postman:inbox'), permanent=True)),
]

django_project/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    # path('', views.home, name='users-home'), ##for function method for view
    path('', views.landing_page, name='landing-page'),
    path('home/', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('load-cities/', views.load_cities, name='ajax_load_cities'),  # <-- added for cities dropdown
]

django_project/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Province(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class City(models.Model):
    province = models.ForeignKey(Province, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100,null=True, blank=True)
    province = models.ForeignKey(Province, on_delete=models.SET_NULL, null=True, blank=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=True)
    postal_code = models.CharField(max_length=7, null=True, blank=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumnail(output_size)
            img.save(self.image.path)

django_project/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, City
from localflavor.ca.forms import CAPostalCodeField
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required Field.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required Field.')
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email already exits!")
        return email

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if first_name.isalpha():
            return first_name
        else:
            raise ValidationError(_('Only alphabet characters are allowed'))

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if last_name.isalpha():
            return last_name
        else:
            raise ValidationError(_('Only alphabet characters are allowed'))


class ProfileRegisterForm(forms.ModelForm):
    postal_code = CAPostalCodeField(required=False)

    class Meta:
        model = Profile
        fields = ['street_address', 'province', 'city', 'postal_code', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
       # self.fields['city'].queryset = City.objects.none()

        # if self.instance.province is not None:
        #     try:
        #         province_id = int(self.data.get('province'))
        #         self.fields['city'].queryset = City.objects.filter(province_id=province_id).order_by('name')
        #     except (ValueError, TypeError):
        #         pass
        if 'province' in self.data:
            try:
                province_id = int(self.data.get('province'))
                self.fields['city'].queryset = City.objects.filter(province_id=province_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['city'].queryset = self.instance.province.city_set.order_by('name')


class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required Field.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required Field.')
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['email'].widget.attrs['readonly'] = True

    def clean_email(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            return instance.email
        else:
            return self.cleaned_data['email']

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if first_name.isalpha():
            return first_name
        else:
            raise ValidationError(_('Only alphabet characters are allowed'))

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if last_name.isalpha():
            return last_name
        else:
            raise ValidationError(_('Only alphabet characters are allowed'))


class ProfileUpdateForm(forms.ModelForm):
    postal_code = CAPostalCodeField(required=False)

    class Meta:
        model = Profile
        fields = ['street_address', 'province', 'city', 'postal_code', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance.province is not None:
            try:
                province_id = int(self.data.get('province'))
                self.fields['city'].queryset = City.objects.filter(province_id=province_id).order_by('name')
            except (ValueError, TypeError):
                pass

django_project/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from users.models import City
from .forms import UserRegisterForm, ProfileRegisterForm, UserUpdateForm, ProfileUpdateForm


def register(request):
    if request.method == 'POST':
        u_form = UserRegisterForm(request.POST)
        p_form = ProfileRegisterForm(request.POST)

        if u_form.is_valid() and p_form.is_valid():
            user = u_form.save()
            user.profile.street_address = p_form.cleaned_data.get('street_address')
            user.profile.city = p_form.cleaned_data.get('city')
            user.profile.province = p_form.cleaned_data.get('province')
            user.profile.postal_code = p_form.cleaned_data.get('postal_code')
            user.profile.image = p_form.cleaned_data.get('image')
            user.profile.save()
            messages.success(request, f'Your account has been created! You can now login!')
            return redirect('login')
    else:
        u_form = UserRegisterForm()  # for first time fetches all fields from forms.py
        p_form = ProfileRegisterForm()

    context = {
        'u_form': u_form, # renders those fetched fields to html form
        'p_form': p_form
    }

    return render(request, 'users/register.html',  context)
    # if validation doesnt go through it redirects to register page with data from form.user


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile.html', context)


def load_cities(request):
    province_id = request.GET.get('province')
    cities = City.objects.filter(province_id=province_id).order_by('name')
    return render(request, 'users/city_dropdown_list_options.html', {'cities': cities})


def landing_page(request):
    return render(request, 'users/index.html', {'title': 'LandingPage'})


def home(request):
    return render(request, 'users/home.html', {'title': 'HomePage'})

django_project/users/templates/users/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

django_project/users/templates/users/home.html
{% extends "base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
</body>
    <div>
        <p><h4>Home page</h4></p>
    </div>
</body>
</html>

django_project/users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load socialaccount %} {% providers_media_js %} <!-- for all auth-->
<html lang="en">
{% block content%}
<div class="row">
    <div class="col-md-4">
    <div class = "content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
                <p><a href="{% provider_login_url 'facebook' %}">Log in With FB</a></p><!-- for all auth-->
                <small class="text-muted ml-2">
                    <a href="{% url 'password_reset' %}">Forgot Password?</a>
                </small>
            </div>
        </form>
        <div class = "border-top pt-3">
            <small class="text-muted">
                Need an account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
    </div>
</div>
{% endblock content %}

django_project/users/templates/users/logout.html
{% extends "base.html" %}
{% block content%}
        <h2>You have been logged out!</h2>
        <div class = "border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'login' %}">Log In Again</a>
            </small>
        </div>
{% endblock content %}

django_project/users/templates/users/password_reset.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content%}
    <div class = "content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password Request</button>
            </div>
        </form>
    </div>
{% endblock content %}

django_project/users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block content%}
        <div class="alert alert-info">
            Your password has been set.
        </div>
        <a href="{% url 'login' %}">Sign In Here</a>
{% endblock content %}

django_project/users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content%}
    <div class = "content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

django_project/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block content%}
        <div class="alert alert-info">
            An email has been sent with instructions to reset your password
        </div>
{% endblock content %}

django_project/users/templates/users/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n static %}{% load postman_tags %}
{% block content%}
<div class="row">
    <div class="col-md-6">

   <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <!-- FORM HERE -->
       <form method="POST" enctype="multipart/form-data" data-cities-url="{% url 'ajax_load_cities' %}"> <!--enctype: saves image in the background -->
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
       </form>
       </div>
    </div>
        <!--  added for dropdown cities      -->
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
          <script>
          $(document).ready(function(){
            $("#id_province").change(function () {
              var url = 'http://'+window.location.hostname + ':8000/load-cities/';
              var provinceId = $(this).val();
              $.ajax({
                url: url,
                data: {
                  'province': provinceId
                },
                success: function (data) {
                  $("#id_city").html(data);
                }
              });
            });
            });
          </script>

           <!-- added for postman -->
           <div class="col-md-4">
             <div class="content-section">
            <h3>Messages</h3>
            <p class='text-muted'>You can put any information here you'd like.
                <ul id="postman_menu">{% postman_unread as unread_count %}
                 <li><a href="{% url 'postman:inbox' %}">&raquo;&nbsp;{% trans "Inbox" %}{% if unread_count %} <strong>({{ unread_count }})</strong>{% endif %}</a></li>
                 <li><a href="{% url 'postman:sent' %}">&raquo;&nbsp;{% trans "Sent Messages" %}</a></li>
                 <li><a href="{% url 'postman:write' %}">&raquo;&nbsp;{% trans "Write" %}</a></li>
                 <li><a href="{% url 'postman:archives' %}">&raquo;&nbsp;{% trans "Archives" %}</a></li>
                 <li><a href="{% url 'postman:trash' %}">&raquo;&nbsp;{% trans "Trash" %}</a></li>
                </ul>
            </p>
            </div>
           </div>

        </div>
{% endblock content %}

django_project/users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content%}
<div class="row">
    <div class="col-md-4">
    <div class = "content-section">
        <form method="POST" enctype="multipart/form-data" data-cities-url="{% url 'ajax_load_cities' %}">
            {% csrf_token %}
            <fieldset class = "form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class = "border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
    </div>
</div>
    <!--    added for cities dropdown -->

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
      <script>
      $(document).ready(function(){
        $("#id_province").change(function () {
          var url = 'http://'+window.location.hostname + ':8000/load-cities/';
          var provinceId = $(this).val();
          console.log('url' + url);
          $.ajax({
            url: url,
            data: {
              'province': provinceId
            },
            success: function (data) {
              $("#id_city").html(data);
            }
          });
        });
        });
      </script>
{% endblock content %}