django_project/community/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views


from community import views
app_name='community'

urlpatterns = [
    url(r'^$', views.QuestionListView.as_view(), name='community_home'),
    url(r'^tag/$', views.TagListView, name='tagged'),
    url(r'^questions/new/$', views.new_question, name='new_question'),
    #url(r'^questions/(?P<question_pk>\d+)/$', views.PostListView.as_view(), name='question_posts'),
    url(r'^questions/(?P<question_pk>\d+)/$', views.post_detail, name='question_posts'),
    # url(r'^questions/(?P<question_pk>\d+)/reply/$', views.reply_question, name='reply_question'),
    url(r'^questions/(?P<question_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='edit_post'),
    url(r'^questions/tagged/(?P<tag_id>\d+)/$', views.tag_question, name='question_tags'),
    url(r'^posts/vote/$', views.upvote, name='upvote'),

]

django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='index'),
    path('', include('users.urls')), # redirects all user apps urls to users -> urls.py
    url(r'^accounts/', include('allauth.urls')),  # new for django all-auth
    url(r'^messages/', include('postman.urls', namespace='postman')), # added for postman
    path('ckeditor/', include('ckeditor_uploader.urls')), #added for ckeditor
    url(r'^community/', include('community.urls')),
    url(r'^garden/',include('garden.urls')),
    url(r'^map/',include('map.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project/map/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = 'map'

urlpatterns =[
    # path(r'', TemplateView.as_view(template_name='map/index.html'), name='map_home'),
    path(r'', views.MapView, name='map_home'),
    path('produce_data/', views.produce_locations, name='loc'),
]

django_project/community/models.py
import math

from django.contrib.auth.models import User
from django.db import models
from django.utils.html import mark_safe
from django.utils.text import Truncator
from django.urls import reverse

from markdown import markdown
from taggit.managers import TaggableManager
import markdown_deux



class Question(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    # topic = models.ForeignKey(Topic, related_name='questions', on_delete=models.CASCADE,)
    message = models.CharField(max_length=4000)
    starter = models.ForeignKey(User, related_name='questions', on_delete=models.CASCADE,)
    views = models.PositiveIntegerField(default=0)
    tags = TaggableManager()


    def __str__(self):
        return self.subject

    def get_page_count(self):
        count = self.posts.count()
        pages = count / 20
        return math.ceil(pages)

    def has_many_pages(self, count=None):
        if count is None:
            count = self.get_page_count()
        return count > 6

    def get_page_range(self):
        count = self.get_page_count()
        if self.has_many_pages(count):
            return range(1, 5)
        return range(1, count + 1)

    def get_last_ten_posts(self):
        return self.posts.order_by('-created_at')[:10]


class Post(models.Model):
    message = models.TextField(max_length=4000)
    question = models.ForeignKey(Question, related_name='posts', on_delete=models.CASCADE,)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE,)
    updated_by = models.ForeignKey(User, null=True, related_name='+', on_delete=models.CASCADE,)
    parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE,)
    votes_total = models.IntegerField(default=0)
    upvote = models.ManyToManyField(User, blank=True, related_name='upvote')
    downvote = models.ManyToManyField(User, blank=True, related_name='downvote')


    class Meta:
        ordering=['-created_at']

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

    def get_absolute_url(self):
        return reverse("community:question_posts", kwargs={"question_pk": self.question.pk})

    def children(self): #replies
        return Post.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

    def total_votes(self):
        self.votes_total = self.upvote - self.downvote
        return self.votes_total






class Vote(models.Model):
    postID = models.ForeignKey(Post,on_delete=models.CASCADE)
    userID = models.ForeignKey(User,on_delete=models.CASCADE)

    class Meta:
        unique_together = ('postID', 'userID')

django_project/community/forms.py
from django import forms

from .models import Post, Question


class NewQuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ['subject', 'message', 'tags']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message', ]

django_project/community/views.py
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import UpdateView, ListView, RedirectView
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.urls import reverse
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

from .forms import NewQuestionForm, PostForm
from .models import Post, Question
from taggit.models import TaggedItemBase, Tag, TaggedItem
import json


###### METHOD TO GET ALL TAGS #############
class TagMixin(object):
    def get_context_data(self, **kwargs):
        context = super(TagMixin, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.filter()
        return context


###########RETRIEVES ALL TAGS ASSOCIATED WITH A SPECFIC QUESTION ##############
class TagIndexView(TagMixin, ListView):
    template_name = 'community/tags.html'
    model = Question
    paginate_by = '10'
    context_object_name = 'questions'

    def get_queryset(self):
        return Question.objects.filter(tags__slug=self.kwargs.get('slug'))


######## DISPLAYS ALL TAGS EXISTING WITH THEIR COUNT #############
def TagListView(request):
    all_tags = Tag.objects.all()
    tag_count = all_tags.annotate(num_times=Count('taggit_taggeditem_items'))

    context = {
        "tags": tag_count,
    }

    return render(request, "community/tags.html", context)



########### QUESTIONS ASSOCIATED WITH A TAG ##############
def tag_question(request, tag_id):

    queryset = Question.objects.filter(tags__id=tag_id)
    tag_name = Tag.objects.filter(id=tag_id)

    context = {
        "object_list": queryset,
        "tag_name": tag_name
    }
    print(context)

    return render(request, "community/question_tags.html", context)

################ SEARCH ALL TAGS - NOT WORKING YET :D #################
# def search(request):
#     found_entries = None
#     if ('q' in request.GET) and request.GET['q'].strip():
#         query_string = request.GET['q']
#         entry_query = get_query(query_string, ['company_name', 'stock_symbol', 'address', 'tags'])
#         found_entries = Company.objects.filter(entry_query).order_by('company_name')\
#             .annotate(num_transcripts=Count('transcripts'))
#
#     return render_to_response('company_list.html', {'all_companies': found_entries})

########## DISPLAYS ALL QUESTIONS ############
class QuestionListView(ListView):
    model = Question
    context_object_name = 'questions'
    template_name = 'community/questions.html'
    paginate_by = 100

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            object_list = self.model.objects.filter(Q(subject__icontains=query) | Q(tags__name__in=query) | Q(message__icontains=query)).distinct()
        else:
            object_list = self.model.objects.all()
        return object_list


#
######### METHOD THAT CREATES A NEW POST FORM ##############
@login_required
def new_question(request):
    if request.method == 'POST':
        form = NewQuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.starter = request.user
            question.save()
            form.save_m2m()
            Post.objects.create(
                message=form.cleaned_data.get('message'),
                question=question,
                created_by=request.user
            )
            return redirect('community:community_home')
    else:
        form = NewQuestionForm()
    return render(request, 'community/new_question.html', {'form': form})


######## METHOD THAT SHOWS POSTS/REPLIES THAT ARE ASSOCIATED WITH A QUESTION ########
class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'community/question_posts.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        session_key = 'viewed_topic_{}'.format(self.question.pk)
        if not self.request.session.get(session_key, False):
            self.question.views += 1
            self.question.save()
            self.request.session[session_key] = True
        kwargs['question'] = self.question
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.question = get_object_or_404(Question, pk=self.kwargs.get('question_pk'))
        queryset = self.question.posts.order_by('created_at')
        return queryset



def post_detail(request, question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    session_key = 'viewed_topic_{}'.format(question_pk)
    if not request.session.get(session_key, False):
        question.views += 1
        question.save()
        request.session[session_key] = True


    form = PostForm(request.POST or None)
    if form.is_valid():
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
            print(parent_id)
        except:
            parent_id = None

        if parent_id:
            parent_qs = Post.objects.filter(pk=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj=parent_qs.first()

        post_obj = form.save(commit=False)
        post_obj.created_by=request.user
        post_obj.question = question
        post_obj.parent = parent_obj
        post_obj.save()



        return HttpResponseRedirect(post_obj.get_absolute_url())

    post = Post.objects.filter(question=question_pk).filter(parent=None)

    context = {
        "instance": question,
        "posts": post,
        "posts_form": form,

    }

    return render(request, "community/question_posts.html", context)





def upvote(request):
    if request.user.is_authenticated:
        post_pk = request.POST.get("id")
        vote_type = request.POST.get("vote_type")
        liked_post = Post.objects.get(pk=post_pk)
        user = request.user

        if vote_type == "up":
            if liked_post.upvote.filter(id=user.id).exists():
                # user has already liked this company
                # remove like/user
                liked_post.upvote.remove(user)
                liked_post.votes_total -= 1
                message = 'You disliked this'
                liked_post.save()

            else:
                # add a new like for a company
                liked_post.upvote.add(user)
                liked_post.votes_total += 1
                message = 'You liked this'
                liked_post.save()
        else:
            if liked_post.downvote.filter(id=user.id).exists():
                # user has already liked this company
                # remove like/user
                liked_post.downvote.remove(user)
                liked_post.votes_total += 1
                message = 'You disliked this'
                liked_post.save()

            else:
                # add a new like for a company
                liked_post.downvote.add(user)
                liked_post.votes_total -= 1
                message = 'You liked this'
                liked_post.save()


        ctx = {'vote_count': liked_post.votes_total}
        return HttpResponse(json.dumps(liked_post.votes_total)) # Sending an success response
    # else:
    #     return JsonResponse("Request method is not a GET")


        # if request.method == 'GET':
        #        post_id = request.GET.get('post_pk')
        #
        #        likedpost = Post.objects.get(pk=post_id) #getting the liked posts
        #        user = request.user
        #
        #        if likedpost.upvote.filter(id=user.id).exists():
        #             # user has already liked this company
        #             # remove like/user
        #             likedpost.votes_total -= 1
        #             message = 'You disliked this'
        #             likedpost.save()
        #
        #        else:
        #             # add a new like for a company
        #             likedpost.upvote.add(user)
        #             likedpost.votes_total += 1
        #             message = 'You liked this'
        #             likedpost.save()
        #
        #        ctx = [{'vote_count': likedpost.votes_total, 'message': message}]
        #        return JsonResponse(ctx, safe=False) # Sending an success response
        # else:
        #        return JsonResponse("Request method is not a GET")


#######METHOD TO REPLY TO A POST ########## as of now you can reply to your own post?
# @login_required
# def reply_question(request, question_pk):
#     question = get_object_or_404(Question, pk=question_pk)
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.question = question
#             post.created_by = request.user
#             post.save()
#
#             question.last_updated = timezone.now()
#             question.save()
#
#             question_url = reverse('community:question_posts', kwargs={'question_pk': question_pk})
#             question_post_url = '{url}?page={page}#{id}'.format(
#                 url=question_url,
#                 id=post.pk,
#                 page=question.get_page_count()
#             )
#
#             return redirect(question_post_url)
#     else:
#         form = PostForm()
#     return render(request, 'community/reply_question.html', {'question': question, 'form': form})
#

########## METHOD TO EDIT YOUR OWN POST ######## must be user that created it
@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    model = Post
    fields = ('message', )
    template_name = 'community/edit_post.html'
    pk_url_kwarg = 'post_pk'

django_project/community/templates/community/question_posts.html
{% extends 'community/community_base.html' %}

{% load gravatar %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_extra%}
{% endblock %}

{% block title %}{{ question.subject }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'community:community_home' %}">Questions</a></li>
  <li class="breadcrumb-item active">{{ question.subject }}</li>
{% endblock %}

{% block sidebar %}
<style>
  .sidebar {
    margin: 0;
    padding: 0;
    width: 200px;
    background-color: #f1f1f1;
    position: fixed;
    height: 100%;
    overflow: auto;
  }

        /* Sidebar links */
  .sidebar a {
    display: block;
    color: black;
    padding: 16px;
    text-decoration: none;
  }

        /* Active/current link */
        .sidebar a.active {
        background-color: #0066ff;
        color: white;
        }

        /* Links on mouse-over */
        .sidebar a:hover:not(.active) {
        background-color: #555;
        color: white;
        }

        /* Page content. The value of the margin-left property should match the value of the sidebar's width property */
        div.content {
          margin-left: 200px;
          padding: 1px 16px;
          height: 1000px;
        }

        /* On screens that are less than 700px wide, make the sidebar into a topbar */
        @media screen and (max-width: 700px) {
          .sidebar {
            width: 100%;
            height: auto;
            position: relative;
          }
          .sidebar a {float: left;}
          div.content {margin-left: 0;}
        }

        /* On screens that are less than 400px, display the bar vertically, instead of horizontally */
        @media screen and (max-width: 400px) {
          .sidebar a {
            text-align: center;
            float: none;
          }
        }

  </style>
  <div class="sidebar">
    <a href="{% url 'community:community_home' %}">All Questions</a>
    <a href="{% url 'community:tagged' %}">Tags</a>
    <a href="#">FAQ</a>
  </div>
{% endblock %}

{% block community_content %}

<!-- QUESTION -->
  <div class="card mb-4 mb-2 border-dark">
    <h5 class="card-header bg-dark text-white">{{ instance.subject }}</h5>
    <div class="card-body">
      <p class="card-text">{{ instance.message }}</p>
    </div>
  </div>
<!-- END QUESTION -->

<br/>

{% if posts %}<h4>Answers</h4>{% endif %}

<div >


{% for post in posts %}
  <hr/>
  <blockquote style=" background: #ffffff;  margin: 1.5em 10px; padding: 0.5em 10px;">
    <div class="row">
      <div class="column">

        <div class="vote-buttons">
          <button type="submit" class="vote" data-id="{{ post.pk }}" data-vote="up" style="background-color: Transparent; border: none; margin-left: 40px;"><i class="fa fa-caret-up" style="font-size:48px;"></i></button>
          <p id="_appendHere{{ post.pk }}" class="_appendHere{{ post.pk }}" data-id="{{ post.pk }}" style="margin-left: 53px;">{{ post.votes_total }}</p>
          <button type="submit" class="vote" data-id="{{ post.pk }}" data-vote="down" style="background-color: Transparent; border: none; margin-left: 40px;"><i class="fa fa-caret-down" style="font-size:48px;"></i></button>
        </div> <!-- .votebuttons -->
      </div>
      <div class="column">
        <br/>
        <p style="margin-left: 40px;"> {{ post.message }} </p>
        {% if post.children.count == 0 %}
          <p style="margin-left: 55px;">via {{ post.created_by.username }} | {{ post.created_at}}</p>
        {% endif %}

        {% if post.children.count == 1 %}
          <p style="margin-left: 55px;">via {{ post.created_by.username }} | {{ post.created_at}} | {{ post.children.count }} Comment</p>
        {% endif %}

        {% if post.children.count > 1 %}
          <p style="margin-left: 55px;">via {{ post.created_by.username }} | {{ post.created_at}} | {{ post.children.count }} Comments</p>
        {% endif %}
      </div>
    </div>

    <style>
      .arrow-up {
        width: 0;
        height: 0;
        border-left: 20px solid transparent;
        border-right: 20px solid transparent;

        border-bottom: 20px solid black;
      }

      .arrow-down {
        width: 0;
        height: 0;
        border-left: 20px solid transparent;
        border-right: 20px solid transparent;

        border-top: 20px solid black;
      }

      .column {
        float: left;
      }

      .left {
        width: 35%;
      }

      .right {
        width: 65%;
      }

    </style>

    <div class="" style=" border-left: 20px solid #ffffff; margin: 10px; margin-left: 85px;">
      <hr/>
    </div>

    <div class="answer-replies"  style=" border-left: 20px solid #ffffff; margin: 10px; margin-left: 85px;">
      {% for child_post in post.children %}

        <p><small>
          {{ child_post.message }} - via {{ child_post.created_by.username }} | {{ child_post.created_at }}
          {% if child_post.created_by == user %}
            |<a href="{% url 'community:edit_post' child_post.question.pk child_post.pk %}"> Edit</a>
          {% endif %}
        </small></p>
          <hr/>
      {% endfor %}

      {% if user.is_authenticated %}
      <a href="#" class="comment-reply-btn">
          <small>Add a Comment</small>
      </a>
      <div class="comment-reply" style="display:none;">

        <form action="." method="POST">
          {% csrf_token %}
          {{ posts_form|crispy }}
          <input type="hidden" name="parent_id" value="{{ post.pk }}">
          <input type="submit" name="" value="Reply" class="btn btn-primary">
        </form>
      </div>
      {% endif %}
    </div>




  </blockquote>
  {% endfor %}
  </div>

  <div class="answer-form">
    <hr/>
    <br/>
    <h4>Your Answer</h4>
    <form action="." method="POST">
      <br/>

      {% csrf_token %}
      {{ posts_form|crispy }}
      <input type="submit" name="" value="Reply" class="btn btn-primary">
    </form>
  </div>


  <!-- JAVASCRIPT -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script type="text/javascript">

    $(document).ready(function(){
      $(".comment-reply-btn").click(function(event){
        console.log("COMMENT REPLY")
        event.preventDefault();
        // stuff = JSON.stringify(this.is_parent());
        // console.log(stuff);
        $(this).next(".comment-reply").fadeToggle();
      });
    });

    $(".vote").click(function () {
      console.log("IN AJAX")
      var id = $(this).data("id"); //get data-id
      console.log(id);
      var vote_type = $(this).data("vote"); //get data-vote
      var score = $('#_appendHere' + id);
      console.log(score)

      $.ajax({
        type: "POST",
        url: "{% url 'community:upvote' %}",
        data: {
          'id': id,
          'vote_type':vote_type,
          csrfmiddlewaretoken: '{{ csrf_token }}'
        },
        success: function (data){
          console.log(data);
          score.html(data);
        }


      })

    });




  </script>
  <!-- END JAVASCRIPT -->

{% include 'community/includes/pagination.html' %}

{% endblock %}

django_project/community/templates/community/question_tags.html
{% extends 'community/community_base.html' %}

{% load gravatar %}

{% block community_content %}
  <div class="mb-4">
    {% for name in tag_name %}
    <h2 style="display:inline-block;">Questions tagged: {{ name }}</h2>
    {% endfor %}
    <a href="{% url 'community:new_question' %}" class="btn btn-primary" style="float:right;">New Question</a>
  </div>



<!-- QUESTIONS ASSOCIATED WITH CERTAIN TAGS.... -->
  <table class="table table-striped mb-4">
    <thead class="thead-inverse">
      <tr>
        <th>Question</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for question in object_list %}
        {% url 'community:question_posts' question.pk as question_url %}
        <tr>
          <td>
            <p class="mb-0">
              <a href="{{ question_url }}" style="font-size: 20px;">{{ question.subject }}</a>

              <style>
              ul#menu li {
                display:inline;
              }
              </style>

              <ul id="menu">


                {% for tag in question.tags.all %}
                  <a href="{% url 'community:question_tags' tag.pk %}" class="btn btn-primary btn-sm"><li> {{ tag }} </li></a>
                {% endfor %}

              </ul>

            </p>
            <small class="text-muted">
              Pages:
              {% for i in question.get_page_range %}
                <a href="{{ question_url }}?page={{ i }}">{{ i }}</a>
              {% endfor %}
              {% if question.has_many_pages %}
              ... <a href="{{ question_url }}?page={{ question.get_page_count }}">Last Page</a>
              {% endif %}
            </small>
          </td>

        </tr>
      {% endfor %}
    </tbody>
  </table>





  {% include 'community/includes/pagination.html' %}

{% endblock %}

django_project/community/templates/community/questions.html
{% extends 'community/community_base.html' %}

{% load static %}
{% load humanize %}

{% block sidebar %}
<style>
  .sidebar {
    margin: 0;
    padding: 0;
    width: 200px;
    background-color: #f1f1f1;
    position: fixed;
    height: 100%;
    overflow: auto;
  }

        /* Sidebar links */
  .sidebar a {
    display: block;
    color: black;
    padding: 16px;
    text-decoration: none;
  }

        /* Active/current link */
        .sidebar a.active {
        background-color: #0066ff;
        color: white;
        }

        /* Links on mouse-over */
        .sidebar a:hover:not(.active) {
        background-color: #555;
        color: white;
        }

        /* Page content. The value of the margin-left property should match the value of the sidebar's width property */
        div.content {
          margin-left: 200px;
          padding: 1px 16px;
          height: 1000px;
        }

        /* On screens that are less than 700px wide, make the sidebar into a topbar */
        @media screen and (max-width: 700px) {
          .sidebar {
            width: 100%;
            height: auto;
            position: relative;
          }
          .sidebar a {float: left;}
          div.content {margin-left: 0;}
        }

        /* On screens that are less than 400px, display the bar vertically, instead of horizontally */
        @media screen and (max-width: 400px) {
          .sidebar a {
            text-align: center;
            float: none;
          }
        }

  </style>
  <div class="sidebar">
    <a class="active" href="{% url 'community:community_home' %}">All Questions</a>
    <a href="{% url 'community:tagged' %}">Tags</a>
    <a href="#">FAQ</a>
  </div>
{% endblock %}

{% block community_content %}
  <div class="mb-4">
    <h2 style="display:inline-block;">All Questions</h2>

    <a href="{% url 'community:new_question' %}" class="btn btn-primary" style="float:right;">New Question</a>

  </div>

  <div class="">
    <form class="" action="" method="GET">
      <input type="text" placeholder="Search Questions" name="q" value="">
      <input type="submit" name="" value="Search">

    </form>
  </div>



  <table class="table table-striped mb-4">
    <thead class="thead-inverse">
      <tr>
        <th>Question</th>
        <th>Starter</th>
        <th>Replies</th>
        <th>Views</th>
        <th>Last Update</th>
      </tr>
    </thead>
    <tbody>
      {% for question in object_list %}
        {% url 'community:question_posts' question.pk as question_url %}
        <tr>
          <td>
            <p class="mb-0">
              <a href="{{ question_url }}" style="font-size: 20px;">{{ question.subject }}</a>

              <style>
              ul#menu li {
                display:inline;
              }
              </style>

              <ul id="menu">


              {% for tag in question.tags.all %}
                <a href="{% url 'community:question_tags' tag.pk %}" class="btn btn-primary btn-sm"><li> {{ tag }} </li></a>
              {% endfor %}

              </ul>

            </p>
            <small class="text-muted">
              Pages:
              {% for i in question.get_page_range %}
                <a href="{{ question_url }}?page={{ i }}">{{ i }}</a>
              {% endfor %}
              {% if question.has_many_pages %}
              ... <a href="{{ question_url }}?page={{ question.get_page_count }}">Last Page</a>
              {% endif %}
            </small>
          </td>
          <td class="align-middle">{{ question.starter.username }}</td>
          <td class="align-middle">{{ question.replies }}</td>
          <td class="align-middle">{{ question.views }}</td>
          <td class="align-middle">{{ question.last_updated|naturaltime }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% include 'community/includes/pagination.html' %}

{% endblock %}

django_project/community/templates/community/tags.html
{% extends 'community/community_base.html' %}

{% load humanize %}

{% block sidebar %}
<style>
  .sidebar {
    margin: 0;
    padding: 0;
    width: 200px;
    background-color: #f1f1f1;
    position: fixed;
    height: 100%;
    overflow: auto;
  }

        /* Sidebar links */
  .sidebar a {
    display: block;
    color: black;
    padding: 16px;
    text-decoration: none;
  }

        /* Active/current link */
        .sidebar a.active {
        background-color: #0066ff;
        color: white;
        }

        /* Links on mouse-over */
        .sidebar a:hover:not(.active) {
        background-color: #555;
        color: white;
        }

        /* Page content. The value of the margin-left property should match the value of the sidebar's width property */
        div.content {
          margin-left: 200px;
          padding: 1px 16px;
          height: 1000px;
        }

        /* On screens that are less than 700px wide, make the sidebar into a topbar */
        @media screen and (max-width: 700px) {
          .sidebar {
            width: 100%;
            height: auto;
            position: relative;
          }
          .sidebar a {float: left;}
          div.content {margin-left: 0;}
        }

        /* On screens that are less than 400px, display the bar vertically, instead of horizontally */
        @media screen and (max-width: 400px) {
          .sidebar a {
            text-align: center;
            float: none;
          }
        }

</style>
  <div class="sidebar">
    <a href="{% url 'community:community_home' %}">All Questions</a>
    <a class="active" href="{% url 'community:tagged' %}">Tags</a>
    <a href="#">FAQ</a>
  </div>
{% endblock %}

{% block community_content %}


  <div class="mb-4">
    <h2 style="display:inline-block;">Tags</h2>
    <a href="{% url 'community:new_question' %}" class="btn btn-primary" style="float:right;">New Question</a>
  </div>

  <div class="">
    <p>A tag is a keyword or label that categorizes your question with other, similar questions. Using the right tags makes it easier for others to find and answer your question.</p>

  </div>


      <div class="row">
      {% for tag in tags %}
          <div class="col-sm-6">
            <div class="img-thumbnail">
              <div class="caption">
                <h3>{{ tag.name }}</h3>
                <p>Number of times tagged: {{ tag.num_times }}</p>

                <a href="{% url 'community:question_tags' tag.pk %}" class="btn btn-primary btn-sm"> Questions </a>



              </div>
            </div>
          </div>

        {% cycle "" "<div class='col-sm-12'><hr/></div></div><div class='row'>" %}
      {% endfor %}
      </div>



  {% include 'community/includes/pagination.html' %}

{% endblock %}